apiVersion: apps/v1
kind: Deployment

metadata:
  name: aman-deploy
  labels:
    first: app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web

    spec:
      containers:
      - name: raj-cont
        image: 3aman/img1:v1.0.0
        ports:
        - containerPort: 7777
      