apiVersion: apps/v1
kind: Deployment
metadata:
  name: aman-deploy 
  labels: 
    first: app

spec: # behaviour of replica set
  replicas: 3
  selectors:
    matchLables:
      app: web
  template:
    metadata:
      labels:
        app: web  
    spec: # behaviour of the pod
      containers: 
        - name: raj-cont
          image: 3aman/img1:v1.0.0
          ports:
            - containerPort: 7777
      