apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: aman-Replica
  labels: 
    app: web

spec: # define the behaviour of replicaset 
  replicas: 3
  selectors: 
    matchLables: 
      web: aman
  template: 
    labels:
      web: aman

spec:  #define bahaviour of the pot
  containers:
    - image: 3aman/img1:v1.0.0
      name: aman-cont
      ports:
        - containerPort: 3333