# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{.values.secret.name}} #aman-secret 
# type: {{.values.secret..type}} #Opaque
# data:
#   DB_User: QURNSU4=
#   DB_Pass: QW1hbjEyMw==

apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.secret.name }}

type: {{ .Values.secret.type }}

data:
  DB_User: {{ .Values.secret.data.DB_User }}
  DB_Pass: {{ .Values.secret.data.DB_Pass }}